version: "3"
services:
  web:
    image:  nginx
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"
    

  loadbalacer: 
    image: jwilder/nginx-proxy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock
      - logvolume: {}
    volumes : 
      logvolume: {}
